### ISSUE TITLE
AUROC curves?

### ISSUE THREAD

**Issue by alopgar** [SamGG/ropls#1]
Hello.
I have not been able to find how to calculate AUROC curves from a ropls object.
Is it implemented as a function? Is there any way of extracting the necessary inputs to apply them to another function?

Thanks a lot!

**Comment by SamGG** [comment]
Hi,
Thanks for your feedback. You reached my repo because I wanted to have a look at this code and maybe tune it. I am not the developer in any way. @ethevenot is still maintaining this package as it is on Bioconductor. I hope he will answer within a few days.
Best.
