### ISSUE TITLE
Creation of substantially different OPLS models depending on the order of the observations

### ISSUE THREAD

**Issue by mattias-erhardsson** [SamGG/ropls#3]
Hi! I've run through the vignette and have been working on a dataset on my own. I've noticed that the constructed model can change dramatically by just changing the order of the observations X matrix/Y vector. For my small dataset of 10 observations and 73 variables, the Q2Y could be 0.281 with one order and 0.573 with another order, with the exact same data. With the bigger data sets of the vignette it seems like the differences are smaller, but the same principle applies.

I thought this was a bit strange, is this an expected behavior?

**Comment by gdmcdonald** [comment]
They seem to do k-fold CV in there somewhere, maybe your reordered points are in different folds?

**Comment by SamGG** [comment]
Hi,
I copied the package because I needed to tweak it, but I don't know the inner parts of package.
You should contact the official maintainer of the package who is Etienne A. Thevenot <etienne.thevenot@cea.fr> or via https://github.com/ethevenot.
Best,
Samuel
