### ISSUE TITLE
Coordinate transform for new points

### ISSUE THREAD

**Issue by gdmcdonald** [SamGG/ropls#4]
Hi Sam, 

I'm wondering if you can help me to work out how to use an OPLS-DA model (from `ropls`) to transform *new* data points that the model wasn't trained on, into the coordinate that best separates the categories, p1. I can't for the life of me get the transform to work right, even to recover the scores for the points the model was trained on.

Cheers,
Gordon

**Comment by SamGG** [comment]
Hi,
I copied the package because I needed to tweak it, but I don't know the inner parts of package.
You should contact the official maintainer of the package who is Etienne A. Thevenot <etienne.thevenot@cea.fr> or via https://github.com/ethevenot.
Best,
Samuel
