### ISSUE TITLE
@subsetVi = numeric(0)

### ISSUE THREAD

**Issue by FrAoJm** [SamGG/ropls#5]
Hi, I am analyzing  a dataset which has a very little variation across the variable I want to predict (case or control), so when I do the opls with orthoI = NA gives me an error:
```
opls(dataMatrixfiltered, conditionFc, predI = 1, orthoI= NA)

Error: No model was built because the predictive component was not significant
```
so I setup orthoI as 0 to get a model of PLS.

When I try to get the confusion matrix using the subsetVi as in the user guide I get the following:
```
trainVi <- getSubsetVi(experiment.oplsda)
trainVi
numeric(0)
```
Is there any way to get something to evaluate the model, even if is not a good one?

Thank you!

**Comment by SamGG** [comment]
@ethevenot could you help, please?

**Comment by ethevenot** [comment]
Hi, the reference repository for the ropls package is Bioconductor (https://www.bioconductor.org/packages/release/bioc/html/ropls.html). Please ask your question on the support there so that I can answer you.
Thanks, Etienne.

**Comment by SamGG** [comment]
@ethevenot did you setup a github repository? If so, I will remove mine immediately, avoiding confusion.

**Comment by FrAoJm** [comment]
Thank you @SamGG  and @ethevenot, I posted in the bioconductor forum. I copy here the link just in case someone arrives here and want to know the answer :=)

https://support.bioconductor.org/p/9138648/

Regards!

**Comment by SamGG** [comment]
Thanks @ethevenot
