### ISSUE TITLE
How to obtain data from inertia barplot and component percentage from plsda model?

### ISSUE THREAD

**Issue by junli1988** [SamGG/ropls#6]
Hi, I want to pull out the data from the PLSDA model and make my own plot with them. I was able to get the scores with the function getScoreMN(). However, I can't find the command for pulling out the component variables and percentage. I read through the vignette and user manual, but I couldn't find a viable command for this purpose. Just started doing PLSDA on Rstudio and quite a noob. Thanks beforehand.

**Comment by SamGG** [comment]
Hi. This repo is mainly for my personal use.
You should contact E. Thevenot
https://github.com/ethevenot
Feel free to add the answer to your question here for the community.
Best.

**Comment by SamGG** [comment]
Hi,
I copied the package because I needed to tweak it, but I don't know the inner parts of package.
You should contact the official maintainer of the package who is Etienne A. Thevenot <etienne.thevenot@cea.fr> or via https://github.com/ethevenot.
Best,
Samuel
