### ISSUE TITLE
How to change the color of a score chart.

### ISSUE THREAD

**Issue by petemeng** [SamGG/ropls#7]
How to change the color of the (O)PLS score plot. This doesn't seem to work.
```
plot(sacurine.pls,type = 'x-score',parPaletteVc=c("red","black"))
```

**Comment by SamGG** [comment]
Hi,
I copied the package because I needed to tweak it, but I don't know the inner parts of package.
You should contact the official maintainer of the package who is Etienne A. Thevenot <etienne.thevenot@cea.fr>?
Best,
Samuel

**Comment by petemeng** [comment]
OK. Thank you!
