### ISSUE TITLE
How to obtain the Orthogonal distance and Score distance？

### ISSUE THREAD

**Issue by JRZL123** [SamGG/ropls#8]
When I run the opls function to perform PLS-DA analysis on the matrix, the Observation Diagnostics shows the OD and SD values. However, I am unable to get these values in the resulting object. Is there a function or Slot that can get these values?

**Comment by SamGG** [comment]
@ethevenot could you give a feedback on this?

**Comment by ethevenot** [comment]
Hi, please use the reference ropls repository on Bioconductor for support. Thank you.
https://bioconductor.org/packages/ropls/

**Comment by SamGG** [comment]
Hi Etienne,
Could you point the URL to create an issue?
Best,
Samuel

**Comment by ethevenot** [comment]
The support is available here:
https://support.bioconductor.org/tag/ropls/
Best,
Etienne.

**Comment by SamGG** [comment]
@JRZL123 please do post your question on the forum.
Best.
